# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
 #   { device = "/dev/disk/by-uuid/d328b607-5406-4fb7-b612-0c57934e3800";
    { device = "/dev/disk/by-uuid/fbec573f-3da3-4d24-aa04-644198af8851";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };
  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/fbec573f-3da3-4d24-aa04-644198af8851";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };
  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/fbec573f-3da3-4d24-aa04-644198af8851";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };
  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/fbec573f-3da3-4d24-aa04-644198af8851";
      fsType = "btrfs";
      options = [ "subvol=@log" ];
    };
  fileSystems."/mnt/btrfs_root" =
    { device = "/dev/disk/by-uuid/fbec573f-3da3-4d24-aa04-644198af8851";
      fsType = "btrfs";
    };
  fileSystems."/home/sinnucso/things" =
    { device = "/dev/disk/by-uuid/fbec573f-3da3-4d24-aa04-644198af8851";
      fsType = "btrfs";
      options = ["subvol=@things"];
    };
  fileSystems."/home/sinnucso/things/steam" =
    { device = "/dev/disk/by-uuid/fbec573f-3da3-4d24-aa04-644198af8851";
      fsType = "btrfs";
      options = ["subvol=@steam"];
    };



  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A352-466E";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
