# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" "sr_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

#  fileSystems."/" =
#    { device = "/dev/disk/by-uuid/48c1542c-fd51-4ea8-9e36-e8e94619df0e";
#      fsType = "btrfs";
#      options = [ "subvol=@" ];
#    };


  fileSystems."/" =
    { device = "/dev/disk/by-uuid/80d6a945-efa2-4032-9f36-6d65438013e0";
      fsType = "btrfs";
      options = [ "subvol=@nix/@root" ];
    };
  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/80d6a945-efa2-4032-9f36-6d65438013e0";
      fsType = "btrfs";
      options = [ "subvol=@nix/@home" ];
    };
  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/80d6a945-efa2-4032-9f36-6d65438013e0";
      fsType = "btrfs";
      options = [ "subvol=@nix/@nix" ];
    };
  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/80d6a945-efa2-4032-9f36-6d65438013e0";
      fsType = "btrfs";
      options = [ "subvol=@nix/@log" ];
    };
  fileSystems."/mnt/btrfs_root" =
    { device = "/dev/disk/by-uuid/80d6a945-efa2-4032-9f36-6d65438013e0";
      fsType = "btrfs";
    };
  fileSystems."/home/sinnucso/storage" =
    { device = "/dev/disk/by-uuid/80d6a945-efa2-4032-9f36-6d65438013e0";
      fsType = "btrfs";
      options = ["subvol=@storage"];
    };



  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7952-A11D";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp4s0f1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
